# Makefile for cmsis

INCLUDES  += -I$(PROJECT)/Core/Include -I$(PROJECT)/Device/Include

DEFINES = -DSTM32F103xB

LDSCRIPT = $(PROJECT)/STM32F103CBTx_FLASH.ld

CCFLAGS = 
 
#LDFLAGS = -lc -L /usr/lib/arm-none-eabi/newlib/ 
#LDFLAGS += -specs=nano.specs -specs=nosys.specs

#LDFLAGS = -L /usr/lib/arm-none-eabi/newlib/ -libc_nano.a

